services:
  app:
    image: docker.io/sivakumar2809/bold-log-viewer:v1.0
    ports:
      - "8080:80"
    volumes:
      - <Path to the logs>:/var/www/html/storage/logs-files
      # Example:
      # - /mnt/d/log-viewer/boldbi/logs:/var/www/html/storage/logs-files
    entrypoint: ["/var/www/html/docker/entrypoint.sh"]
    environment:
      - APP_KEY=base64:NIzboDNT/6lkHihOokQF6fYETAbNbMiJkHYCFkezXDo=
      - APP_ENV=local
      - APP_DEBUG=true
      # - CACHE_DRIVER=file
